---
title: Programming Languages for Data Science
date: "2019-09-03T10:00:00Z"
external_link: ""
image:
  caption: "[Photo by Markus Spiske on Unsplash](https://unsplash.com/photos/8OyKWQgBsKQ)"
  focal_point: Smart
summary: Unterlagen für Programming Languages for Data Science.
description: Unterlagen für das Seminar Programming Languages for Data Science - SQL, R, Markdown, PostgreSQL. 
tags:
- R
- SQL
- Markdown
- DataScience
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
links:
#- icon: file
#  icon_pack: fas
#  name: demo slides
#  url: ../../slides/r-for-data-science/r-for-data-science.html
#- icon: github
#  icon_pack: fab
#  name: demo code
#  url: https://github.com/kirenz/xaringan/blob/master/xaringan-demo-slides.Rmd
#- icon: book
#  icon_pack: fas
#  name: Documentation
#  url: https://slides.yihui.name/xaringan/#1
---

# Agenda

## Einführung

* [Einführung in Business Intelligence](https://www.kirenz.com/slides/intro-business-intelligence/assets/player/keynotedhtmlplayer#0)


* [First steps in Markdown](https://www.kirenz.com/slides/markdown-first-steps/markdown-guide.html#1)

---

## SQL

* Datenexploration (Selektieren, Ordnen und Filtern)

* Datentypen und Datentransformationen

* Gruppieren und Aggregieren

* Tabellen verbinden (Joins)

* Tabellen modifizieren

* Subqueries

* [Microsoft Azure SQL Database](https://github.com/kirenz/microsoft_azure_sql_database)


_Literatur:_  

DeBarros, A. (2018). Practical SQL: A Beginner's Guide to Storytelling with Data. No Starch Press.  


---

## R for Data Science

* [First Steps in R](https://www.dropbox.com/s/ul7btvtp30627s6/R_overview.pdf?dl=0)

* [Introduction to Data Science with R](https://www.kirenz.com/slides/r-for-data-science/assets/player/keynotedhtmlplayer#0)

* [Einführung in die deskriptive Statistik in R](https://www.kirenz.de/post/2019-08-01-r-descriptive-statistics/)

* [Basic Analytics in R](https://www.dropbox.com/sh/wmbf2syk2ijpbyn/AAAH5jPQUbmE5wGiiWCTzePEa?dl=0)

* [Data Exploration in R](https://www.dropbox.com/sh/rjvsa79zx76h67w/AADx2bd4_cifjwnHTlQyAen6a?dl=0)

* Correlation Analysis in R, [interactive  module](https://www.dropbox.com/sh/png707v3hn1wt6l/AAAmtxYR43bPZASY2ILzMT7Ea?dl=0), [HTML](https://www.dropbox.com/s/ob14w7jrwa7mv30/Correlation.html?dl=0)

* [Natural Language Processing with R](https://www.dropbox.com/sh/zsqxpdpe99mrqss/AACZypuVKWEOmceaddxGlRBJa?dl=0)

* [Advanced Programming in R, Part I](https://www.dropbox.com/s/q7up3x819bg44f4/r-programming.pdf?dl=0)

* [Erstellung von interaktiven Tutorials in R](https://github.com/kirenz/interaktive_tutorials_mit_r_erstellen)




_Literatur:_  


* [Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc.](https://r4ds.had.co.nz)

* [Wickham, H. (2019). Advanced r. Chapman and Hall/CRC.](https://adv-r.hadley.nz) 

* [Silge, J., & Robinson, D. (2017). Text mining with R: A tidy approach. "O'Reilly Media, Inc."](https://www.tidytextmining.com)

* [Xie, Y. (2019). Bookdown: Authoring Books and Technical Documents with R Markdown. Chapman and Hall/CRC.](https://bookdown.org/yihui/bookdown/)


