<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.3.1">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Jan Kirenz">

  
  
  
    
  
  <meta name="description" content="Test">

  
  <link rel="alternate" hreflang="en-us" href="/post/2019-08-01-regression_happy/">

  


  

  
  
  
  <meta name="theme-color" content="#E13D3D">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/paraiso-light.min.css" crossorigin="anonymous" title="hl-light">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/paraiso-light.min.css" crossorigin="anonymous" title="hl-dark" disabled>
      
    

    

    

  

  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Arapey:400,400i|Karla:400,700|Roboto+Mono|Open Sans:300">
  

  
  
  
  <link rel="stylesheet" href="/css/academic.min.1322fc49e20b88c93e5b9cdb13456289.css">

  
    
    
    
    
      
    
    
    
    <link rel="stylesheet" href="/css/academic.8fa6fab8892f3fb614ebe2b828140a5f.css">
  

  
  
  

  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/2019-08-01-regression_happy/">

  
  
  
  
    
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="og:site_name" content="Jan Kirenz">
  <meta property="og:url" content="/post/2019-08-01-regression_happy/">
  <meta property="og:title" content="Regression World Happiness | Jan Kirenz">
  <meta property="og:description" content="Test"><meta property="og:image" content="/post/2019-08-01-regression_happy/featured.jpg">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2019-08-02T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2019-08-02T00:00:00&#43;00:00">
  

  

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
  window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#E13D3D",
          "text": "#ffffff"
        },
        "button": {
          "background": "#ffffff",
          "text": "#E13D3D"
        }
      },
      "theme": "classic",
      "content": {
        "message": "This website uses cookies to ensure you get the best experience on our website.",
        "dismiss": "Got it!",
        "link": "Learn more",
        "href": "https://cookies.insites.com"
      }
    })});
</script>



  





  <title>Regression World Happiness | Jan Kirenz</title>

</head>


<body id="top" data-spy="scroll" data-target="#TableOfContents" data-offset="71" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" role="textbox" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/">Jan Kirenz</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/post"><span>Blog</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/talks"><span>Teaching</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/projects"><span>Resources</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/contact"><span>Contact</span></a>
        </li>

        
        

      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article" itemscope itemtype="http://schema.org/Article">

  













<div class="article-header d-xl-none">
  <div class="featured-image" style="background-image: url('/post/2019-08-01-regression_happy/featured_hua0d4d4b24f4da3a102e4452ac738b95f_330304_800x0_resize_q90_lanczos.jpg');"></div>
  <span class="article-header-caption"><a href="https://unsplash.com/photos/ZV_64LdGoao" target="_blank">Photo by Pankaj Patel on Unsplash</a></span>
</div>


<div class="container-fluid split-header d-none d-xl-block">
  <div class="row">
    <div class="col-6">
      <div class="split-header-content">
        <h1 itemprop="name">Regression World Happiness</h1>

        

        



<meta content="2019-08-02 00:00:00 &#43;0000 UTC" itemprop="datePublished">
<meta content="2019-08-02 00:00:00 &#43;0000 UTC" itemprop="dateModified">

<div class="article-metadata">

  
  
  
  
  <div>
    



  <span itemprop="author name" itemtype="http://schema.org/Person"><a href="/authors/alison/">Jan Kirenz</a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
    
    <time>Aug 2, 2019</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    17 min read
  </span>
  

  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    <a href="/categories/blogdown/">blogdown</a>, <a href="/categories/r/">R</a></span>
  

  

</div>


        















        
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/2019-08-01-regression_happy/&amp;text=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/2019-08-01-regression_happy/&amp;t=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Regression%20World%20Happiness&amp;body=/post/2019-08-01-regression_happy/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/2019-08-01-regression_happy/&amp;title=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Regression%20World%20Happiness%20/post/2019-08-01-regression_happy/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/2019-08-01-regression_happy/&amp;title=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


      </div>
    </div>
    <div class="col-6">
      <div class="split-header-image">
        <img src="/post/2019-08-01-regression_happy/featured_hua0d4d4b24f4da3a102e4452ac738b95f_330304_680x500_fill_q90_lanczos_smart1.jpg" itemprop="image" alt="">
        <span class="article-header-caption"><a href="https://unsplash.com/photos/ZV_64LdGoao" target="_blank">Photo by Pankaj Patel on Unsplash</a></span>
      </div>
    </div>
  </div>
</div>

<div class="article-container d-xl-none">
  <h1 itemprop="name">Regression World Happiness</h1>

  

  



<meta content="2019-08-02 00:00:00 &#43;0000 UTC" itemprop="datePublished">
<meta content="2019-08-02 00:00:00 &#43;0000 UTC" itemprop="dateModified">

<div class="article-metadata">

  
  
  
  
  <div>
    



  <span itemprop="author name" itemtype="http://schema.org/Person"><a href="/authors/alison/">Jan Kirenz</a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
    
    <time>Aug 2, 2019</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    17 min read
  </span>
  

  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    <a href="/categories/blogdown/">blogdown</a>, <a href="/categories/r/">R</a></span>
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/2019-08-01-regression_happy/&amp;text=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/2019-08-01-regression_happy/&amp;t=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Regression%20World%20Happiness&amp;body=/post/2019-08-01-regression_happy/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/2019-08-01-regression_happy/&amp;title=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Regression%20World%20Happiness%20/post/2019-08-01-regression_happy/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/2019-08-01-regression_happy/&amp;title=Regression%20World%20Happiness" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

  














</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      

<div id="TOC">
<ul>
<li><a href="#regression"><span class="toc-section-number">1</span> Regression</a></li>
<li><a href="#data-import"><span class="toc-section-number">2</span> Data import</a></li>
<li><a href="#einfache-regression"><span class="toc-section-number">3</span> 1) EINFACHE REGRESSION</a></li>
</ul>
</div>

<div id="regression" class="section level1">
<h1><span class="header-section-number">1</span> Regression</h1>
<div class="figure">
<img src="whr16.jpg" alt="World Happiness Report 2016" />
<p class="caption">World Happiness Report 2016</p>
</div>
<p>The World Happiness Report 2016, which ranks 156 countries by their happiness levels, was released in Rome in advance of UN World Happiness Day, March 20th. The rankings come from the Gallup World Poll and are based on answers to the main life evaluation question asked in the poll. This is called the Cantril ladder: it asks respondents to think of a ladder, with the best possible life for them being a 10, and the worst possible life being a 0. They are then asked to rate their own current lives on that 0 to 10 scale.</p>
<p>The rankings are from nationally representative samples, for the years 2013-2015. They are based entirely on the survey scores, using the Gallup weights to make the estimates representative. The variables in the dataset show the estimated extent to which each of six factors – levels of GDP, life expectancy, generosity, social support, freedom, and corruption – contribute to making life evaluations higher in each country than they are in Dystopia, a hypothetical country that has values equal to the world’s lowest national averages for each of the six factors (see <a href="https://worldhappiness.report/faq/">FAQs: What is Dystopia?</a>).</p>
<p><em>Learn more about the data on the <a href="https://worldhappiness.report">World Happines Report Homepage</a></em></p>
<p><a href="https://s3.amazonaws.com/happiness-report/2016/HR-V1_web.pdf">Source: Helliwell, J., Layard, R., &amp; Sachs, J. (2016). World Happiness Report 2016, Update (Vol. I). New York: Sustainable Development Solutions Network.</a></p>
</div>
<div id="data-import" class="section level1">
<h1><span class="header-section-number">2</span> Data import</h1>
<p>Let’s start by creating a variable called link to store the link to the data file, which is located at GitHub.</p>
<pre class="r"><code># create variable to store url
link &lt;- &quot;https://raw.githubusercontent.com/kirenz/datasets/master/happy.csv&quot;</code></pre>
<pre class="r"><code>library(readr) # load the readr package
report &lt;- read_csv(link) </code></pre>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1]</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   X1 = col_double(),
##   Country = col_character(),
##   Happiness.Score = col_double(),
##   Economy..GDP.per.Capita. = col_double(),
##   Family = col_double(),
##   Health..Life.Expectancy. = col_double(),
##   Trust..Government.Corruption. = col_double()
## )</code></pre>
<p>Daten sichten:</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attache Paket: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>glimpse(report)</code></pre>
<pre><code>## Observations: 157
## Variables: 7
## $ X1                            &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,…
## $ Country                       &lt;chr&gt; &quot;Denmark&quot;, &quot;Switzerland&quot;, &quot;Iceland…
## $ Happiness.Score               &lt;dbl&gt; 7.526, 7.509, 7.501, 7.498, 7.413,…
## $ Economy..GDP.per.Capita.      &lt;dbl&gt; 1.44178, 1.52733, 1.42666, 1.57744…
## $ Family                        &lt;dbl&gt; 1.16374, 1.14524, 1.18326, 1.12690…
## $ Health..Life.Expectancy.      &lt;dbl&gt; 0.79504, 0.86303, 0.86733, 0.79579…
## $ Trust..Government.Corruption. &lt;dbl&gt; 0.44453, 0.41203, 0.14975, 0.35776…</code></pre>
<pre class="r"><code>anyNA(report) # Prüfung auf fehlende Werte</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Datenanpassung:</p>
<pre class="r"><code>report$X1 &lt;- NULL # Löschung von X1

library(dplyr)
report &lt;- rename(report, happy = Happiness.Score) # Umbenennung 
report &lt;- rename(report, gdp_capita = Economy..GDP.per.Capita.  ) # Umbenennung 
report &lt;- rename(report, life_expect = Health..Life.Expectancy.) # Umbenennung 
report &lt;- rename(report, trust = Trust..Government.Corruption.) # Umbenennung </code></pre>
<p>Daten erneut sichten:</p>
<pre class="r"><code>library(dplyr)
glimpse(report)</code></pre>
<pre><code>## Observations: 157
## Variables: 6
## $ Country     &lt;chr&gt; &quot;Denmark&quot;, &quot;Switzerland&quot;, &quot;Iceland&quot;, &quot;Norway&quot;, &quot;Finl…
## $ happy       &lt;dbl&gt; 7.526, 7.509, 7.501, 7.498, 7.413, 7.404, 7.339, 7.3…
## $ gdp_capita  &lt;dbl&gt; 1.44178, 1.52733, 1.42666, 1.57744, 1.40598, 1.44015…
## $ Family      &lt;dbl&gt; 1.16374, 1.14524, 1.18326, 1.12690, 1.13464, 1.09610…
## $ life_expect &lt;dbl&gt; 0.79504, 0.86303, 0.86733, 0.79579, 0.81091, 0.82760…
## $ trust       &lt;dbl&gt; 0.44453, 0.41203, 0.14975, 0.35776, 0.41004, 0.31329…</code></pre>
</div>
<div id="einfache-regression" class="section level1">
<h1><span class="header-section-number">3</span> 1) EINFACHE REGRESSION</h1>
<div id="a-visuelle-prufung-des-linearen-zusammenhangs" class="section level4">
<h4><span class="header-section-number">3.0.0.1</span> a) Visuelle Prüfung des linearen Zusammenhangs</h4>
<p>Prüfung mit einem Plot, ob die Annahme eines linearen Zusammenhangs zwischen “happy” und “Health..Life.Expectancy.” plausibel erscheint. Interpretieren Sie das Schaubild.</p>
<pre class="r"><code>library(ggplot2)

ggplot(report) +
  geom_point(aes(x=life_expect, y=happy)) +
  theme_light() </code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Interpretation:</p>
<p>Mögliche Lösung:
Ein positiver linearer Zusammenhang ist erkennbar, jedoch nicht in allen Wertebereichen deutlich ausgeprägt. Bei Werten von “Health…”&quot; kleiner als 0.25 kanne eine Abweichung von dem linearen Zusammenhnag beobachtet werden.</p>
</div>
<div id="b-regressionsmodell" class="section level4">
<h4><span class="header-section-number">3.0.0.2</span> b) Regressionsmodell</h4>
<p>Erzeugung eines einfachen Regressionsmodells mit Y = <code>happy</code> und X = <code>life_expect</code>. Interpretieren Sie die Regressionskoeffizienten (Vorzeichen, Ausprägung und Signifikanz) und den <span class="math inline">\(R^2\)</span>. Beschreiben Sie konkret, welche Änderung von Y bei einer Erhöhung von X um eine Einheit erwartet wird. Beschreiben Sie zudem, wie der Wert der Konstante interpretiert werden kann.</p>
<pre class="r"><code>lm &lt;- lm(formula = happy ~ life_expect, data= report) # Modell aufstellen</code></pre>
<pre class="r"><code>summary(lm) # Zusammenfssung der Modellergebnisse  ausgeben</code></pre>
<pre><code>## 
## Call:
## lm(formula = happy ~ life_expect, data = report)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.58873 -0.52304 -0.00744  0.54591  1.74549 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.2577     0.1551   21.01   &lt;2e-16 ***
## life_expect   3.8100     0.2573   14.81   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7371 on 155 degrees of freedom
## Multiple R-squared:  0.5858, Adjusted R-squared:  0.5831 
## F-statistic: 219.2 on 1 and 155 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpretation:</p>
<p>Lösung:
Beide Koeffizienten (Konstante und Regressionskoeffizient der Variable “Health…”) sind höchst signifikant. Wenn die unabhängigen Variable <code>life_expect</code> auf 0 gesetzt wird, schätzt unser Modell eine Happiness Score von 3.2577. Der Regressionskoeffizient der unabhängigen Variable “Health…” beträgt 3.81. D.h. bei einer Erhöhung dieser Variablen um eine Einheit erhöht sich die abhängige Variable “Happiness Score” um 3.81 Einheiten.
Der <span class="math inline">\(R^2\)</span> beträgt 0.5858, d.h. ca. 58% der Streuung von Y kann von X erklärt werden.</p>
</div>
<div id="c-residuen-und-prognosegute-mse-und-rmse" class="section level4">
<h4><span class="header-section-number">3.0.0.3</span> c) Residuen und Prognosegüte: MSE und RMSE</h4>
<p>Die mittlere quadratische Abweichung (mean squared error, MSE) und die Wurzel der mittleren quadratischen Abweichung (root mean squared error, RMSE) bzw. residual standard error (Terminologie in R) sind Kennzahlen zur Beurteilung der Prognosegüte. Sie geben an, wie gut sich das Regressionsmodell an die Beobachtungswerte anpasst bzw.wie stark eine Prognose im Durchschnitt von den tatsächlichen Werten abweicht.</p>
<p>Bei der Funktion für MSE befindet sich im Zähler die quadrierte Summe der Residuen (residual sum of squares, RSS) und im Nenner die Anzahl der Beobachtungen (n).</p>
<p>Bei der Funktion für RMSE ziehen wir die Wurzel des folgenden Bruchs:</p>
<ul>
<li>Zähler: die quadrierte Summe der Residuen (residual sum of squares, RSS).</li>
<li>Nenner: der Anzahl der Beobachtungen (n) abzüglich 1 (für die Konstante) und
p (Anzahl der Variablen in der Regression). D.h. Wurzel von (n-1-p). (n-1-p) entspricht den Freiheitsgraden (degrees of freedom).</li>
</ul>
<p>Berechnung des MSE mit der bereitgestellten Formel:</p>
<p><span class="math display">\[ MSE = \frac{RSS}{df} \]</span>
* MSE = Mean Squared Error (mittlere quadratische Abweichung)
* RSS = Residual Sum of Squares (Residuenquadratsumme)
* df = Degrees of Freedom (Freitheitsgrade)</p>
<p>Die Freiheitsgrade sind wie folgt zu berechen:</p>
<p><span class="math display">\[ MSE = \frac{RSS}{n - p -1} \]</span></p>
<p><em>Hinweise zu den Freiheitsgraden</em></p>
<p>Dies ist die Anzahl der unabhängigen, d.h. frei verfügbaren Beobachtungen. Wenn bspw. nur zwei Beobachtungen existieren würden, kann damit zwar eine Regression gerechnet werden, jedoch würden sich beide Werte zwingend direkt auf der Regressionsgeraden befinden (d.h. die Gerade hat keine “Freiheit” sich zwischen den Werten anzupassen).</p>
<p>Freiheitsgrade werden durch die Anzahl der Beobachtungswerte und der Anzahl an unabhängigen Variablen bestimmt. Je mehr unabhängige Variablen in einem Modell enthalten sind (bei einer gegebenen Anzahl an Beobachtungswerten), desto geringer die Anzahl der Freiheitsgrade. Die Formel für die Berechnung der Freiheitsgrade (degrees of freedom) lautet:</p>
<p><span class="math display">\[ df = n - p -1 \]</span>
* n = Anzahl der Beobachtungswerte
* p = Anzahl der unabhängigen Variablen
* 1 = Konstante (Intercept)</p>
<p>Alternativ kann die Konstante auch in p integriert werden. Dies wird in Lehrbüchern unterschiedlich gehandhabt.</p>
<p>Berechnung von MSE:</p>
<pre class="r"><code>mse &lt;-  sum((residuals(lm)^2) / df.residual(lm)) #df.residuals = degrees of freedom
print(mse)</code></pre>
<pre><code>## [1] 0.5433417</code></pre>
<p>Berechnung des RMSE (Sie finden diesen Wert ebenfalls in Aufgabe 1b in dem regression summary mit der Bezeichnung <code>residual standard error</code>)</p>
<pre class="r"><code>rmse &lt;- sqrt(sum((residuals(lm)^2) / df.residual(lm)))
print(rmse)</code></pre>
<pre><code>## [1] 0.7371171</code></pre>
</div>
<div id="aufgabe-1-geben-sie-an-folgende-werte-an-n-p-und-df.-2-nehmen-sie-an-wir-wurden-ein-weiteres-modell-aufstellen-und-erhalten-einen-rmse-von-0.9-anstelle-von-0.7371171.-wie-beurteilen-sie-das-neue-modell-anhand-dieser-kennzahl-welches-modell-ist-vorzuziehen" class="section level4">
<h4><span class="header-section-number">3.0.0.4</span> Aufgabe: (1) Geben Sie an folgende Werte an: n, p und df. (2) Nehmen Sie an, wir würden ein weiteres Modell aufstellen und erhalten einen RMSE von 0.9 anstelle von 0.7371171. Wie beurteilen Sie das neue Modell anhand dieser Kennzahl (welches Modell ist vorzuziehen)?</h4>
<p>Antwort:</p>
<p>Lösung:
n= 157, p =1 und df=155
Modell 1 ist vorzuziehen, da dieses einen geringeren MSE aufweist</p>
</div>
<div id="d-konfidenzintervall" class="section level4">
<h4><span class="header-section-number">3.0.0.5</span> d) Konfidenzintervall</h4>
<p>Interpretation der Konfidenzintervalle (95%) der beiden Regressionskoeffizienten.</p>
<pre class="r"><code>confint(lm, level = 0.95)</code></pre>
<pre><code>##                2.5 %   97.5 %
## (Intercept) 2.951319 3.564001
## life_expect 3.301683 4.318305</code></pre>
<p>Interpretation:</p>
<p>Lösung:
Bei einem Konfidenzintervall mit der gewählten Sicherheit von 95% umschließen die Intervallgrenzen in 95 % der Fälle den wahren Parameter und in 5 % der Fälle nicht. Die Breite des Konfidenzintervalls wird als Präzision der Schätzung bezeichnet.</p>
</div>
<div id="e-durchfuhrung-und-interpretation-der-regression-diagnostics-mit-hilfe-von-plots" class="section level4">
<h4><span class="header-section-number">3.0.0.6</span> e) Durchführung und Interpretation der “Regression Diagnostics” mit Hilfe von Plots</h4>
<p>(Residuals vs Fitted, Normal Q-Q, Scale-Location, Residulas vs Leverage)</p>
<pre class="r"><code>par(mfrow =c(2,2))
plot(lm)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Interpretation:</p>
<p>Lösung: Abgesehen von einigen Ausreißern (insbesondere die Beobachtungswerte 76, 103 und 156) sind keine Besonderheiten in den Plots zu erkennen.</p>
</div>
<div id="f-auffallige-falle-in-einem-plot-markieren" class="section level4">
<h4><span class="header-section-number">3.0.0.7</span> f) Auffällige Fälle in einem Plot markieren</h4>
<p>Was können Sie über die in dem Plot markierten Fälle (76, 103 und 156) aussagen? X-Achse = prognostizierte Werte und Y = tatsächliche Werte (mit Werte=happy).</p>
<pre class="r"><code>report$y_hat &lt;- lm$fitted.values # Prognosen der Funktion
ggplot(report) +
  geom_smooth(method = &quot;lm&quot;, aes(x=y_hat, y=happy)) +
  geom_point(aes(x=y_hat, y=happy)) +
  theme_light() +
  geom_point(data=report[76,], (aes(x=y_hat, y=happy)), color=&quot;red&quot;) +
  geom_point(data=report[103,], (aes(x=y_hat, y=happy)), color=&quot;green&quot;) +
  geom_point(data=report[156,], (aes(x=y_hat, y=happy)), color=&quot;blue&quot;) +
  geom_text(data=report[76,], (aes(x=y_hat, y=happy)), label=c(&quot;76&quot;), hjust=0, vjust=0.5) +
  geom_text(data=report[103,], (aes(x=y_hat, y=happy)), label=c(&quot;103&quot;), hjust=0, vjust=0.5) +
  geom_text(data=report[156,], (aes(x=y_hat, y=happy)), label=c(&quot;156&quot;), hjust=0, vjust=0.5) +
  labs(x=&#39;Prognostizierte Werte (Fitted values)&#39;, y=&#39;Tatsächliche Werte&#39;) </code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="g-regressionsmodell-anpassen" class="section level4">
<h4><span class="header-section-number">3.0.0.8</span> g) Regressionsmodell anpassen</h4>
<p>Die Fälle 76, 103 und 156 werden entfernt und das Regressionsmodell erneut berechnet. Interpretieren Sie das neue Modell (insbesondere die Koeffizienten und den <span class="math inline">\(R^2\)</span>)</p>
<pre class="r"><code>report2 &lt;- report[-c(76,103,156),] # Entfernung der Fälle 
lm_2 &lt;- lm(formula = happy ~ life_expect, data= report2)
summary(lm_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = happy ~ life_expect, data = report2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.6453 -0.5204  0.0268  0.5446  1.5036 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.1314     0.1500   20.87   &lt;2e-16 ***
## life_expect   4.0275     0.2475   16.27   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6886 on 152 degrees of freedom
## Multiple R-squared:  0.6354, Adjusted R-squared:  0.633 
## F-statistic: 264.9 on 1 and 152 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>coef(lm_2)</code></pre>
<pre><code>## (Intercept) life_expect 
##    3.131353    4.027535</code></pre>
</div>
<div id="h-erneute-interpretation-von-mse-und-rmse-siehe-aufgabe-1c" class="section level4">
<h4><span class="header-section-number">3.0.0.9</span> h) Erneute Interpretation von MSE und RMSE (siehe Aufgabe 1c)</h4>
<pre class="r"><code>mse2 &lt;-  sum((residuals(lm_2)^2) / df.residual(lm_2))
print(mse2)</code></pre>
<pre><code>## [1] 0.4741907</code></pre>
<pre class="r"><code>rmse2 &lt;- sqrt(sum((residuals(lm_2)^2) / df.residual(lm_2)))
print(rmse2)</code></pre>
<pre><code>## [1] 0.688615</code></pre>
<p>Interpretation:</p>
<pre class="r"><code>report2$y_hat &lt;- lm_2$fitted.values # Prognosen der Funktion
ggplot(report2) +
  geom_smooth(method = &quot;lm&quot;, aes(x=y_hat, y=happy)) +
  geom_point(aes(x=y_hat, y=happy)) +
  theme_light() +
  labs(x=&#39;Prognostizierte Werte (Fitted values)&#39;, y=&#39;Tatsächliche Werte&#39;) </code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Lösung: Durch die Entfernung der Ausreißer erzielen wir eine Verbesserung bei den beiden Kennzahlen.</p>
</div>
<div id="multiple-regression-variablenauswahl-model-subset-selection" class="section level2">
<h2><span class="header-section-number">3.1</span> 2) MULTIPLE REGRESSION &amp; VARIABLENAUSWAHL (MODEL SUBSET SELECTION)</h2>
<div id="a-regressionsmodelle-mittels-vorwartsselektion-aufstellen" class="section level4">
<h4><span class="header-section-number">3.1.0.1</span> a) Regressionsmodelle mittels Vorwärtsselektion aufstellen</h4>
<p>Es soll automatisiert geprüft werden, welche Variablen in das Modell mit aufgenommen werden sollten: Abhängige Variable: “happy” ; Mögliche unabhängige Variablen: “gdp_capita”, “Family”, “life_expect”, “trust”</p>
<p>Hinweis: in R kann das <a href="https://cran.r-project.org/web/packages/leaps/leaps.pdf">Paket leaps</a> für die Durchführung der Vorwärtsselektion und Rückwärtsselektion genutzt werden.</p>
<ul>
<li>Vorgabe 1: Ermittlung der aufzunehmenden Variablen mittels <strong>Vorwärtsslektion</strong> (forward selection)<br />
</li>
<li>Vorgabe 2: Ausgabe der folgenden Kennzahlen: Residuenquadratsumme (RSS) und das adjustierte Bestimmtheitsmaß (auch bereinigtes, korrigiertes oder angepasstes Bestimmtheitsmaß bzw. R-Quadrat genannt).</li>
<li>Vorgabe 3: Darstellung der Kennzahlen für die unterschiedliche Anzahl an Variablen in einem Plot.</li>
<li>Aufgabe 1: Interpretation der Ergebnisse: was ist die optimalen Anzahl an Variablen in dem Modell?</li>
<li>Vorgabe 4: Ausgabe der Koeffizienten eines beliebigen Modells (hier Modell 4)</li>
<li>Aufgabe 2: Prüfung Multikollinearität des vierten Modells (mit Varianzinflationsfaktor (VIF). Wir nutzen die folgende (vereinfachte) Interpretation des VIF: 1 = not correlated; Between 1 and 5 = moderately correlated; Greater than 5 = highly correlated. Interpretieren Sie zudem 3 beliebige Ergebnisse des Korrelationsplots.</li>
</ul>
<p>Hinweis: Bei den Vorgaben müssen jeweils keine Angaben gemacht werden - diese dienen lediglich als Vorlagen für die separat gekennzeichneten Interpretationsaufgaben.</p>
</div>
<div id="vorgabe-1" class="section level4">
<h4><span class="header-section-number">3.1.0.2</span> Vorgabe 1</h4>
<pre class="r"><code>library(leaps)
report_subset &lt;- report[,2:6] 
regfit_f &lt;- regsubsets(happy ~., data = report_subset, method =&#39;forward&#39;) # der &quot;.&quot; bedeutet, dass alle unabhängigen Variablen genutzt werden sollen 
regfit_sum_f &lt;- summary(regfit_f)
print(regfit_sum_f)</code></pre>
<pre><code>## Subset selection object
## Call: regsubsets.formula(happy ~ ., data = report_subset, method = &quot;forward&quot;)
## 4 Variables  (and intercept)
##             Forced in Forced out
## gdp_capita      FALSE      FALSE
## Family          FALSE      FALSE
## life_expect     FALSE      FALSE
## trust           FALSE      FALSE
## 1 subsets of each size up to 4
## Selection Algorithm: forward
##          gdp_capita Family life_expect trust
## 1  ( 1 ) &quot;*&quot;        &quot; &quot;    &quot; &quot;         &quot; &quot;  
## 2  ( 1 ) &quot;*&quot;        &quot;*&quot;    &quot; &quot;         &quot; &quot;  
## 3  ( 1 ) &quot;*&quot;        &quot;*&quot;    &quot; &quot;         &quot;*&quot;  
## 4  ( 1 ) &quot;*&quot;        &quot;*&quot;    &quot;*&quot;         &quot;*&quot;</code></pre>
</div>
<div id="vorgabe-2" class="section level4">
<h4><span class="header-section-number">3.1.0.3</span> Vorgabe 2</h4>
<pre class="r"><code>print(regfit_sum_f$rss) # RSS</code></pre>
<pre><code>## [1] 76.32950 60.06118 54.12827 48.25632</code></pre>
<pre class="r"><code>print(regfit_sum_f$adjr2) # Angepasster R Quadrat</code></pre>
<pre><code>## [1] 0.6221870 0.7007809 0.7285756 0.7564283</code></pre>
</div>
<div id="vorgabe-3" class="section level4">
<h4><span class="header-section-number">3.1.0.4</span> Vorgabe 3</h4>
<pre class="r"><code>par(mfrow =c(1,2))
plot(regfit_sum_f$adjr2,xlab=&quot;Anzahl Variablen&quot;,ylab=&quot;Adj. Rsq&quot;,type=&quot;l&quot;, xaxt = &#39;n&#39;)
axis(1, at = 1:4)
plot(regfit_sum_f$rss,xlab=&quot;Anzahl Variablen&quot;,ylab=&quot;Res.Quad.Summe&quot;,type=&quot;l&quot;, xaxt = &#39;n&#39;)
axis(1, at = 1:4)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre class="r"><code>plot(regfit_f, scale=&quot;adjr2&quot;)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
<div id="aufgabe-1" class="section level4">
<h4><span class="header-section-number">3.1.0.5</span> Aufgabe 1</h4>
<p>Interpretation:</p>
<p>Lösung:</p>
<p>Interpretation: Das Modell mit vier unabhängigen Variablen hat laut RSS und angepasster <span class="math inline">\(R^2\)</span> die besten Werte erzielt. Hier muss jedoch berücksichtigt werden, dass die Evaluierung nur auf Grundlage der “Trainingsdaten” und nicht anhand von “Testdaten” erfolgte. In der Regel führt das Hinzufügen von weiteren unabhängigen Variablen immer zu einer Reduzierung der Residuenquadratsumme (RSS) und Erhöhung des angepassten <span class="math inline">\(R^2\)</span>. Aus diesem Grund sollte eine Modell-Evaluierung anhand von Testdaten erfolgen.</p>
<p>In unserem Fall wäre es sinnvoll, den relativen Zugewinn, welcher durch das Hinzufügen von weiteren unabhängigen Variablen verursacht wird, zu berücksichtigen. Zwar handelt es sich hier nicht um die typische Bias-Varianz-Problematik, jedoch wird mit zunehmender Anzahl an unabhängigen Variablen das Modell komplexer.</p>
<p>Wie aus den Daten ersichtlich wird, führt das Hinzufügen der zweiten unabhängigen Variablen zu der größten Reduzierung der RSS bzw. Erhöhung des angepassten <span class="math inline">\(R^2\)</span>. Dagegen führt das Hinzufügen der dritten und vierten unabhängigen Variablen zu relativ geringen Modellverbesserungen. Beispielsweise wird die Residuenquadratsumme durch die Variable 4 lediglich um 5.87195 reduziert (RSS-Reduktion von 54.12827 aud 48.25632). Besonders deutlich wird der marginale Zugewinn bei Betrachtung des angepassten <span class="math inline">\(R^2\)</span>, welcher sich lediglich um 0.0278527 verbessert (von 0.7285756 auf 0.7564283).</p>
<p>Aus den oben genannten Gründen kann - je nach Argumentation - das Modell 2,3 oder 4 als “optimales” Modell bezeichnet werden. Da wir in dieser Aufgabe explizit nur die Trainingsdaten und speziell RSS und angepasstes <span class="math inline">\(R^2\)</span> als zu optimierende Kennzahlen berücksichtigen, wird das Modell 4 als optimals Modell gewählt.</p>
</div>
<div id="vorgabe-4" class="section level4">
<h4><span class="header-section-number">3.1.0.6</span> Vorgabe 4:</h4>
<pre class="r"><code>coef(regfit_f,4)</code></pre>
<pre><code>## (Intercept)  gdp_capita      Family life_expect       trust 
##   2.4199123   0.6544712   1.5397474   1.5498788   1.8293911</code></pre>
</div>
<div id="aufgabe-2" class="section level4">
<h4><span class="header-section-number">3.1.0.7</span> Aufgabe 2:</h4>
<pre class="r"><code>library(car)</code></pre>
<pre><code>## Lade nötiges Paket: carData</code></pre>
<pre><code>## 
## Attache Paket: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre class="r"><code>model_4 &lt;- lm(happy ~.,report_subset)
summary(model_4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = happy ~ ., data = report_subset)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.48624 -0.32416  0.00008  0.33598  1.75442 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.4199     0.1491  16.230  &lt; 2e-16 ***
## gdp_capita    0.6545     0.2202   2.972  0.00344 ** 
## Family        1.5397     0.2283   6.744 3.03e-10 ***
## life_expect   1.5499     0.3604   4.301 3.03e-05 ***
## trust         1.8294     0.4252   4.302 3.01e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5634 on 152 degrees of freedom
## Multiple R-squared:  0.7627, Adjusted R-squared:  0.7564 
## F-statistic: 122.1 on 4 and 152 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>vif_4 &lt;- vif(model_4)
print(vif_4)</code></pre>
<pre><code>##  gdp_capita      Family life_expect       trust 
##    4.056237    1.822089    3.356853    1.095368</code></pre>
<p>Regel: 1 = not correlated; between 1 and 5 = moderately correlated; greater than 5 = highly correlated. Keine Anzeichen für Probleme bezüglich Multikollinearität.</p>
<pre class="r"><code>library(corrplot)</code></pre>
<pre><code>## corrplot 0.84 loaded</code></pre>
<pre class="r"><code>cordata = cor(report_subset)
corrplot(cordata, method = &quot;number&quot;)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
<div id="b-regressionsmodelle-mittels-ruckwartsselektion-aufstellen" class="section level4">
<h4><span class="header-section-number">3.1.0.8</span> b) Regressionsmodelle mittels Rückwärtsselektion aufstellen</h4>
<p>EEs soll automatisiert geprüft werden, welche Variablen in das Modell mit aufgenommen werden sollten: Abhängige Variable: “happy” ; Mögliche unabhängige Variablen: “gdp_capita”, “Family”, “life_expect”, “trust”</p>
<ul>
<li>Vorgabe 1: Ermittlung der aufzunehmenden Variablen mittels <strong>Rückwärtsselektion</strong> (backward selection)</li>
<li>Vorgabe 2: Ausgabe der folgenden Kennzahlen: Residuenquadratsumme (RSS) und das adjustierte Bestimmtheitsmaß (auch bereinigtes, korrigiertes oder angepasstes Bestimmtheitsmaß bzw. R-Quadrat genannt).</li>
<li>Vorgabe 3: Darstellung der Kennzahlen für die unterschiedliche Anzahl an Variablen in einem Plot.</li>
<li>Aufgabe 1: Interpretation der Ergebnisse: was ist die optimalen Anzahl an Variablen in dem Modell?</li>
<li>Vorgabe 4: Ausgabe der Koeffizienten eines beliebigen Modells (hier Modell 4)</li>
<li>Aufgabe 2: Prüfung Multikollinearität des vierten Modells (mit Varianzinflationsfaktor (VIF). Wir nutzen die folgende (vereinfachte) Interpretation des VIF: 1 = not correlated; Between 1 and 5 = moderately correlated; Greater than 5 = highly correlated. Interpretieren Sie zudem 3 beliebige Ergebnisse des Korrelationsplots.</li>
</ul>
<p>Hinweis: Bei den Vorgaben müssen jeweils keine Angaben gemacht werden - diese dienen lediglich als Vorlagen für die separat gekennzeichneten Interpretationsaufgaben.</p>
</div>
<div id="vorgabe-1-1" class="section level4">
<h4><span class="header-section-number">3.1.0.9</span> Vorgabe 1</h4>
<pre class="r"><code>regfit_b &lt;- regsubsets(happy ~.,report_subset, method =&#39;backward&#39;)
regfit_sum_b &lt;- summary(regfit_b)
print(regfit_sum_b)</code></pre>
<pre><code>## Subset selection object
## Call: regsubsets.formula(happy ~ ., report_subset, method = &quot;backward&quot;)
## 4 Variables  (and intercept)
##             Forced in Forced out
## gdp_capita      FALSE      FALSE
## Family          FALSE      FALSE
## life_expect     FALSE      FALSE
## trust           FALSE      FALSE
## 1 subsets of each size up to 4
## Selection Algorithm: backward
##          gdp_capita Family life_expect trust
## 1  ( 1 ) &quot; &quot;        &quot; &quot;    &quot;*&quot;         &quot; &quot;  
## 2  ( 1 ) &quot; &quot;        &quot;*&quot;    &quot;*&quot;         &quot; &quot;  
## 3  ( 1 ) &quot; &quot;        &quot;*&quot;    &quot;*&quot;         &quot;*&quot;  
## 4  ( 1 ) &quot;*&quot;        &quot;*&quot;    &quot;*&quot;         &quot;*&quot;</code></pre>
</div>
<div id="vorgabe-2-1" class="section level4">
<h4><span class="header-section-number">3.1.0.10</span> Vorgabe 2</h4>
<pre class="r"><code>print(regfit_sum_b$rss) # RSS</code></pre>
<pre><code>## [1] 84.21796 58.25813 51.06067 48.25632</code></pre>
<pre class="r"><code>print(regfit_sum_b$adjr2) # Angepasster R Quadrat</code></pre>
<pre><code>## [1] 0.5831410 0.7097635 0.7439580 0.7564283</code></pre>
</div>
<div id="vorgabe-3-1" class="section level4">
<h4><span class="header-section-number">3.1.0.11</span> Vorgabe 3</h4>
<pre class="r"><code>par(mfrow =c(1,2))
plot(regfit_sum_b$adjr2,xlab=&quot;Anzahl Variablen&quot;,ylab=&quot;Adj. Rsq&quot;,type=&quot;l&quot;, xaxt = &#39;n&#39;)
axis(1, at = 1:4)
plot(regfit_sum_b$rss,xlab=&quot;Anzahl Variablen&quot;,ylab=&quot;Res.Quad.Summe&quot;,type=&quot;l&quot;, xaxt = &#39;n&#39;)
axis(1, at = 1:4)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<pre class="r"><code>plot(regfit_b, scale=&quot;adjr2&quot;)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
</div>
<div id="aufgabe-1-1" class="section level4">
<h4><span class="header-section-number">3.1.0.12</span> Aufgabe 1</h4>
<p>Interpretation</p>
<p>Lösung: wie zuvor</p>
<pre class="r"><code>which.min(regfit_sum_f$rss)</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>which.max(regfit_sum_f$adjr2)</code></pre>
<pre><code>## [1] 4</code></pre>
<p><em>Optional: Bezeichnung des optimalen Modells</em></p>
<pre class="r"><code>par(mfrow =c(1,1))
plot(regfit_sum_f$rss,xlab =&quot;Anzahl Variablen&quot;,ylab=&quot;RSS&quot;,type=&#39;l&#39;, xaxt =&#39;n&#39;)
axis(1, at = 1:4)
points(4, regfit_sum_f$rss[4], col =&quot;red&quot;,cex =4, pch =20)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
</div>
<div id="aufgabe-2-1" class="section level4">
<h4><span class="header-section-number">3.1.0.13</span> Aufgabe 2:</h4>
<pre class="r"><code># muss angepasst werden - hier muss die Korr. berechnet werden
#model_b_4 &lt;- lm(happy ~.,regfit_b)
#vif_4 &lt;- vif(regfit_b)
#print(vif_4)</code></pre>
<p>Regel: 1 = not correlated; between 1 and 5 = moderately correlated; greater than 5 = highly correlated. Keine Anzeichen für Probleme bezüglich Multikollinearität.</p>
<pre class="r"><code>#library(corrplot)
#cordata = cor(report_subset)
#corrplot(cordata, method = &quot;number&quot;)</code></pre>
<pre class="r"><code>#coef(regfit_b,4)</code></pre>
<p>Interpretation:</p>
<p>Lösung: keine Probleme mit Multikollinearität.</p>
<hr />
</div>
</div>
<div id="resampling" class="section level2">
<h2><span class="header-section-number">3.2</span> 3) RESAMPLING</h2>
<p>In den folgenden Aufgaben nutzen wir die Daten aus Aufgabe 1a)</p>
<div id="a-k-fache-kreuzvalidierung-k-fold-cross-validation" class="section level3">
<h3><span class="header-section-number">3.2.1</span> a) k-fache Kreuzvalidierung (k-Fold Cross Validation)</h3>
<p>Erstellung von zwei Modellen mit Kreuzvalidierung (k=10) und Ausgabe des MSE. Interpretieren Sie den MSE.</p>
<ul>
<li>Modell 1: Y = <code>happy</code>; X: <code>life_expect</code></li>
<li>Modell 2: Y = <code>happy</code>; X: &quot;<code>gdp_capita</code>, <code>Family</code>, <code>life_expect</code>, <code>trust</code></li>
</ul>
<p>Hinweis: in R kann das Paket “boot” für die Durchführung der k-fachen Kreuzvalidierung genutzt werden. Zudem kann in boot der Befehl foo$delta[1] für die Ausgabe des MSE genutzt werden. (foo ist ein Platzhalter für die Bezeichnung des erstellten Modells).</p>
<pre class="r"><code>library(boot)</code></pre>
<pre><code>## 
## Attache Paket: &#39;boot&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     logit</code></pre>
<pre class="r"><code>set.seed(20)

report_fold &lt;- report[,2:6]

# Modell 1
modell_1 &lt;- glm(formula = happy ~ life_expect, data= report_fold)

mse_1 &lt;- cv.glm(report_fold, modell_1, K=10)$delta[1]
print(mse_1)</code></pre>
<pre><code>## [1] 0.5516518</code></pre>
<pre class="r"><code># Modell 2
modell_2 &lt;- glm(formula = happy ~ ., data= report_fold)

mse_2 &lt;- cv.glm(report_fold, modell_2, K=10)$delta[1]
print(mse_2)</code></pre>
<pre><code>## [1] 0.3319973</code></pre>
</div>
<div id="b-wiederholte-k-fache-kreuzvalidierung-mit-gleichem-modell" class="section level3">
<h3><span class="header-section-number">3.2.2</span> b) Wiederholte k-fache Kreuzvalidierung mit gleichem Modell</h3>
<p>Wir möchten untersuchen, wie stark der MSE bei wiederholter Durchführung der k-fachen Kreuzvalidierung schwankt. Interpretieren Sie das Ergebnis.</p>
<p>Erstellung eines Modells mit 10-facher Kreuzvalidierung (k=10) und 4 Wiederholungen. Ausgabe aller 4 MSE (mit einem for loop).</p>
<ul>
<li>Modell: Y = happy; X: “gdp_capita”, “Family”, “life_expect”, “trust”</li>
</ul>
<pre class="r"><code>library(boot)
set.seed(20)

mse_4 = rep(0,4)
for (i in 1:4) {
  glm_report_4 &lt;- glm(happy ~ .,data=report_fold)
  mse_4[i] &lt;- cv.glm(report_fold, glm_report_4, K=10)$delta[1]
}
print(mse_4)</code></pre>
<pre><code>## [1] 0.3372849 0.3319973 0.3408791 0.3350908</code></pre>
<p>Interpretation:</p>
<p>Lösung: Nur leichte Schwankungen erkennbar.</p>
</div>
<div id="c-k-fache-kreuzvalidierung-mit-unterschiedlichen-modellen" class="section level3">
<h3><span class="header-section-number">3.2.3</span> c) k-fache Kreuzvalidierung mit unterschiedlichen Modellen</h3>
<p>Wir wollen nun die Prognosegüte unterschiedlicher Modelle miteinander vergleichen. Dazu nutzen wir unterschiedliche polynomiale Grade (1 bis 8)</p>
<p>Erstellung von 8 Modellen mit jeweils 10-facher Kreuzvalidierung (k=10) und unterschiedlichen polynomialen Graden (1 bis 8 mit einem for loop). Darstellung der MSE der jeweiligen Modelle mit einem Plot.</p>
<ul>
<li>Modell: Y = happy; X: life_expect</li>
</ul>
<pre class="r"><code>library(boot)
set.seed(20)

mse_8= rep(0,8)
for (i in 1:8) {
  glm_report_kv8 &lt;- glm(happy ~ poly(life_expect, i),data=report_fold)
  mse_8[i] &lt;- cv.glm(report_fold, glm_report_kv8, K=10)$delta[1]
}
print(mse_8)</code></pre>
<pre><code>## [1] 0.5516518 0.5279303 0.5134770 0.5316689 0.5158378 0.5229267 0.6101607
## [8] 0.5342106</code></pre>
<pre class="r"><code>which.min(mse_8) # Identifikation der geringsten Ausprägung </code></pre>
<pre><code>## [1] 3</code></pre>
<p>Erstellung eines Plots:</p>
<pre class="r"><code>polynom &lt;- (1:8)
kv &lt;- data.frame(mse_8, polynom)
kv &lt;- kv[order(polynom),] 

ggplot(kv, aes(x=as.factor(polynom))) +
  geom_point(aes(y=mse_8), color = &quot;red&quot;)+ 
  geom_line(aes(y=mse_8, group = 1), color = &quot;red&quot;) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0, size = 8, family=&quot;Arial&quot;, colour=&#39;black&#39;),
        axis.text.y = element_text(angle = 0, size = 8, family=&quot;Arial&quot;, colour=&#39;black&#39;),
        axis.title = element_text(size=8, face=&quot;bold&quot;, family=&quot;Arial&quot;, colour=&#39;black&#39;),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title=element_text(hjust=0, size=10,  family=&quot;Arial&quot;, face=&quot;bold&quot;, colour=&#39;black&#39;)) +
  labs(y = &quot;Mean Squared Error (MSE)&quot;, x=&quot;Grad des Polynoms&quot;, title=&quot;10-fache Kreuzvalidierung&quot;)</code></pre>
<p><img src="/post/2019-08-01-regression_happy/index_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>Interpretation:</p>
<p>Lösung:
Im Rahmen der Validierung hat das Modell mit dem dritten polynomialen Grad das beste Ergebnis erzielt.</p>
</div>
</div>
</div>

    </div>

    

<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/blogdown/">blogdown</a>
  
</div>



    
      








  
  
    
  
  





  
  
  
    
  
  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    
      
      <img class="portrait mr-3" src="/authors/alison/avatar_hu1d623008f699678abc0368ff80db1811_316634_250x250_fill_q90_lanczos_center.jpg" itemprop="image" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/">Jan Kirenz</a></h5>
      <h6 class="card-subtitle">Professor</h6>
      <p class="card-text" itemprop="description">I&rsquo;m a data scientist educator and consultant.</p>
      <ul class="network-icon" aria-hidden="true">
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="/contact" >
              <i class="fas fa-paper-plane"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://github.com/kirenz" target="_blank" rel="noopener">
              <i class="fab fa-github"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://www.xing.com/profile/Jan_Kirenz" target="_blank" rel="noopener">
              <i class="fab fa-xing"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://www.linkedin.com/in/jan-kirenz-01b301a5/" target="_blank" rel="noopener">
              <i class="fab fa-linkedin-in"></i>
            </a>
          </li>
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/post/2019-07-20-up-and-running-with-blogdown/">Up &amp; Running with blogdown</a></li>
          
          <li><a href="/talk/2019-web-analytics/">Web Analytics &amp; Social Media Analytics</a></li>
          
        </ul>
      </div>
      
    

    

    


  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/css.min.js"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/bash.min.js"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/js.min.js"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/markdown.min.js"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/html.min.js"></script>
        
      

      
      
    

    
    

    
    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.9ef1b53ee2bde6c7f33b150c6ba4d452.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    <a href="/license/">LICENSE: CC-BY-SA <br> <i class="fab fa-creative-commons fa-2x"></i><i class="fab fa-creative-commons-by fa-2x"></i><i class="fab fa-creative-commons-sa fa-2x"></i> </a><br>
  </p>
  

  <p class="powered-by">
    &copy; Jan Kirenz, 2019 &middot; 

    Made with the <a href="https://cran.r-project.org/" target="_blank" rel="noopener"><i class="fab fa-r-project"></i> </a><a href="https://github.com/rstudio/blogdown" target="_blank" rel="noopener">blogdown</a> package and the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>. Source code available at 
    <a href="https://github.com/rbind/apreshill" target="_blank" rel="noopener"><i class="fas fa-code-branch" style="color:#E13D3D"></i></a>

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
